version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: ucc_postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=cyberpassword2026
      - POSTGRES_DB=nist_5g_ucc
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: ucc_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://admin:cyberpassword2026@db:5432/nist_5g_ucc
      - JWT_SECRET=supersecretcyberkey
    depends_on:
      - db

  frontend:
    build: ./nist-5g-dashboard
    container_name: ucc_frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend

volumes:
  postgres_data:
